#pragma once

#define NUM_STRIPS 8

#define NUM_LEDS_STRIP_0 240
#define NUM_LEDS_STRIP_1 300
#define NUM_LEDS_STRIP_2 300
#define NUM_LEDS_STRIP_3 300
#define NUM_LEDS_STRIP_4 300
#define NUM_LEDS_STRIP_5 300
#define NUM_LEDS_STRIP_6 300
#define NUM_LEDS_STRIP_7 300

#define NUM_LEDS	NUM_LEDS_STRIP_0 + \
					NUM_LEDS_STRIP_1 + \
					NUM_LEDS_STRIP_2 + \
					NUM_LEDS_STRIP_3 + \
					NUM_LEDS_STRIP_4 + \
					NUM_LEDS_STRIP_5 + \
					NUM_LEDS_STRIP_6 + \
					NUM_LEDS_STRIP_7

#define STRIP_PIN_0 13
#define STRIP_PIN_1 12
#define STRIP_PIN_2 27
#define STRIP_PIN_3 33
#define STRIP_PIN_4 15
#define STRIP_PIN_5 32
#define STRIP_PIN_6 14
#define STRIP_PIN_7 SCL

#define LED_TYPE WS2812B
#define COLOR_ORDER GRB

#define MILLI_AMPS 60000

#define FRAMES_PER_SECOND